package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"

	"sdk_version_control/internal/sdk"
)

func extractVersionFromOutput(cmd string, args []string) string {
	fullPath := resolveCommand(cmd)
	if fullPath == "" {
		return ""
	}
	c := createCmd(fullPath, args...)
	sysPath := sdk.GetSystemPath()
	if sysPath != "" {
		c.Env = append(os.Environ(), "PATH="+sysPath)
	}
	out, err := c.CombinedOutput()
	if err != nil {
		return ""
	}
	return extractVersionFromString(string(out))
}

// extractVersionFromString applies the version-extraction regex to a command's
// raw output. Used by extractVersionFromOutput (system-detected SDKs) and
// detectVersionFromDir (imported SDKs). Returns "" if no version pattern found.
func extractVersionFromString(s string) string {
	re := regexp.MustCompile(`(\d+\.\d+(?:\.\d+)?)`)
	return re.FindString(s)
}

func (a *App) detectVersionFromDir(sdkRoot string, f sdk.VersionFetcher) (string, error) {
	cmdName, args := f.VerifyCommand()
	sdkType := string(f.Type())

	binDir := sdkRoot
	if d := filepath.Join(sdkRoot, "bin"); isDir(d) {
		binDir = d
	}

	binPath := findExecutable(binDir, cmdName)
	if binPath == "" {
		return "", fmt.Errorf("%s executable not found in directory", cmdName)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	c := createCmdContext(ctx, binPath, args...)

	env := os.Environ()
	sysPath := sdk.GetSystemPath()
	extraPath := binDir
	if sysPath != "" {
		extraPath = binDir + string(os.PathListSeparator) + sysPath
	}
	env = append(env, "PATH="+extraPath)

	if sdkType == "maven" || sdkType == "gradle" {
		javaHome := a.findJavaHome()
		if javaHome == "" {
			return "", fmt.Errorf("importing %s requires JDK to be installed first, please import or install JDK first", sdkType)
		}
		env = append(env, "JAVA_HOME="+javaHome)
	}

	if sdkType == "android" {
		javaHome := a.findJavaHome()
		if javaHome != "" {
			env = append(env, "JAVA_HOME="+javaHome)
		}
	}

	c.Env = env
	out, err := c.CombinedOutput()
	if err != nil {
		if ctx.Err() == context.DeadlineExceeded {
			return "", fmt.Errorf("executing %s timed out (10s), unable to get version", cmdName)
		}
		return "", fmt.Errorf("failed to execute %s: %s", cmdName, strings.TrimSpace(string(out)))
	}

	ver := extractVersionFromString(string(out))
	if ver == "" {
		return "", fmt.Errorf("unable to parse version from %s output", cmdName)
	}
	return ver, nil
}

func findExecutable(dir, name string) string {
	exts := []string{""}
	if runtime.GOOS == "windows" {
		exts = []string{".exe", ".cmd", ".bat", ""}
	}
	for _, ext := range exts {
		p := filepath.Join(dir, name+ext)
		if info, err := os.Stat(p); err == nil && !info.IsDir() {
			return p
		}
	}
	return ""
}

func (a *App) findJavaHome() string {
	jdkDir := a.cfg.SdkDir("jdk")
	activeVersion := a.cfg.GetActiveVersion("jdk")
	if activeVersion != "" {
		jdkRoot := filepath.Join(jdkDir, activeVersion)
		if isDir(jdkRoot) {
			return jdkRoot
		}
	}
	if entries, err := os.ReadDir(jdkDir); err == nil {
		for _, e := range entries {
			if e.IsDir() {
				return filepath.Join(jdkDir, e.Name())
			}
		}
	}
	if jh := os.Getenv("JAVA_HOME"); jh != "" && isDir(jh) {
		return jh
	}
	return ""
}

func isDir(p string) bool {
	info, err := os.Stat(p)
	return err == nil && info.IsDir()
}

// resolveCommand resolves a command name to its full path using the system PATH.
// Returns "" when the command is not found (matching exec.LookPath semantics).
// The SVC-managed shims directory (~/.svc/shims) is excluded: shims there are
// generated by this app and route to the active SDK version. Finding a shim
// instead of a real system binary would mislead ImportPathSdk (importing the
// shim instead of the real SDK) and GetAllSdkStatus (reporting the SVC version
// as a system PATH version).
func resolveCommand(cmd string) string {
	sysPath := sdk.GetSystemPath()
	sep := string(os.PathListSeparator)
	exts := []string{""}
	if runtime.GOOS == "windows" {
		exts = []string{"", ".exe", ".cmd", ".bat"}
	}
	shimsDir := sdk.SvcShimsDir()
	for _, dir := range strings.Split(sysPath, sep) {
		dir = strings.TrimSpace(dir)
		if dir == "" {
			continue
		}
		if sdk.IsShimsDirEntry(dir, shimsDir) {
			continue
		}
		for _, ext := range exts {
			p := filepath.Join(dir, cmd+ext)
			if info, err := os.Stat(p); err == nil && !info.IsDir() {
				return p
			}
		}
	}
	if p, err := exec.LookPath(cmd); err == nil {
		if !sdk.IsShimsPath(p, shimsDir) {
			return p
		}
	}
	return ""
}
