package helpers

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"svc/internal/sdk"
)

// FindExecutable looks for name (plus platform extensions on Windows) inside
// dir and returns the first regular file found, or "".
func FindExecutable(dir, name string) string {
	exts := []string{""}
	if runtime.GOOS == "windows" {
		exts = []string{".exe", ".cmd", ".bat", ""}
	}
	for _, ext := range exts {
		p := filepath.Join(dir, name+ext)
		if info, err := os.Stat(p); err == nil && !info.IsDir() {
			return p
		}
	}
	return ""
}

// IsDir reports whether p exists and is a directory.
func IsDir(p string) bool {
	info, err := os.Stat(p)
	return err == nil && info.IsDir()
}

// ResolveCommand resolves a command name to its full path using the system PATH.
// Returns "" when the command is not found (matching exec.LookPath semantics).
// The SVC-managed shims directory (~/.svc/shims) is excluded: shims there are
// generated by this app and route to the active SDK version. Finding a shim
// instead of a real system binary would mislead ImportPathSdk (importing the
// shim instead of the real SDK) and GetAllSdkStatus (reporting the SVC version
// as a system PATH version).
func ResolveCommand(cmd string) string {
	sysPath := sdk.GetSystemPath()
	sep := string(os.PathListSeparator)
	exts := []string{""}
	if runtime.GOOS == "windows" {
		exts = []string{"", ".exe", ".cmd", ".bat"}
	}
	shimsDir := sdk.SvcShimsDir()
	for _, dir := range strings.Split(sysPath, sep) {
		dir = strings.TrimSpace(dir)
		if dir == "" {
			continue
		}
		if sdk.IsShimsDirEntry(dir, shimsDir) {
			continue
		}
		for _, ext := range exts {
			p := filepath.Join(dir, cmd+ext)
			if info, err := os.Stat(p); err == nil && !info.IsDir() {
				return p
			}
		}
	}
	if p, err := exec.LookPath(cmd); err == nil {
		if !sdk.IsShimsPath(p, shimsDir) {
			return p
		}
	}
	return ""
}
