//go:build !windows

package shimmanager

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"sdk_version_control/internal/config"
	"sdk_version_control/internal/logger"
)

// shellSingleQuote wraps s in single quotes for POSIX shells; an embedded
// single quote is escaped the standard POSIX way (end the quoted run, add a
// backslash-escaped quote, reopen quoting). Unlike fmt %q (double quotes), a
// single-quoted value is fully inert when the rc file is sourced: $, `, and
// \ are NOT re-expanded, so a tampered env-var value cannot execute
// commands. Item 8.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// fishEscape escapes s for use as an UNQUOTED fish word by backslash-
// escaping shell metacharacters and whitespace. Fish has no $VAR expansion
// inside the values we write, but it does split on unescaped whitespace and
// interpret ;|&<>()$ etc., so those must be escaped rather than wrapping
// the whole value in double quotes (fish double quotes still expand $ and
// command substitutions). Item 6.
func fishEscape(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '/' || r == '.' || r == '_' || r == '-' || r == ':' || r == '+' || r == '@':
			// Path-safe punctuation that needs no escaping.
			b.WriteRune(r)
		default:
			b.WriteByte('\\')
			b.WriteRune(r)
		}
	}
	return b.String()
}

// generateRcContent generates the .svc.rc shell script content (Unix).
func (m *Manager) generateRcContent(envVars []envVarEntry) string {
	svcHome := m.cfg.SvcDir()
	home := m.cfg.HomeDir()

	var lines []string
	lines = append(lines, "# ~/.svc.rc - Managed by SVC. You may edit manually.")
	lines = append(lines, "# This file is sourced by your shell (one line added to .zshrc/.bashrc).")
	lines = append(lines, "# Do not move this file; SVC reads it from this exact location.")
	lines = append(lines, "")

	// Use SVC_HOME variable so migration only needs updating one line.
	// The default form keeps "$HOME/.svc" double-quoted on purpose so $HOME
	// expands; a custom (absolute) svcHome is single-quoted because it is a
	// literal path that must stay inert.
	if svcHome == filepath.Join(home, ".svc") {
		lines = append(lines, `export SVC_HOME="$HOME/.svc"`)
	} else {
		lines = append(lines, fmt.Sprintf("export SVC_HOME=%s", shellSingleQuote(svcHome)))
	}
	lines = append(lines, `export PATH="$SVC_HOME/shims:$PATH"`)

	if len(envVars) > 0 {
		lines = append(lines, "")
		lines = append(lines, "# SDK environment variables (updated on version switch)")
		for _, e := range envVars {
			// Item 8: absolute value, single-quoted. (The previous version
			// rewrote values as "$SVC_HOME/..." and used %q; a $ reference
			// cannot survive single-quoting, and %q leaves $/` expandable.)
			lines = append(lines, fmt.Sprintf("export %s=%s", e.Key, shellSingleQuote(e.Value)))
		}
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

// applyEnvVarsToSystem is a no-op on Unix: env vars are written to .svc.rc
// (which shells source) by updateRcFile, so there is no separate system store
// to update. Exists only to mirror the Windows contract.
func (m *Manager) applyEnvVarsToSystem(envVars []envVarEntry) {}

// removeEnvVarsFromSystem is a no-op on Unix: dropping the SDK's lines from
// .svc.rc (regenerated by updateRcFile) is the only removal path. Exists only
// to mirror the Windows contract.
func (m *Manager) removeEnvVarsFromSystem(keys []string) {}

// ensurePathEntry adds the source line to the user's default shell rc (one-time).
func (m *Manager) ensurePathEntry() error {
	// Detect default shell
	shell := os.Getenv("SHELL")
	defaultShell := ""
	if strings.Contains(shell, "zsh") {
		defaultShell = "zsh"
	} else if strings.Contains(shell, "bash") {
		defaultShell = "bash"
	} else if strings.Contains(shell, "fish") {
		defaultShell = "fish"
	}

	// Add source line to default shell rc
	written := 0
	if defaultShell != "" {
		if err := m.addSourceLine(defaultShell); err != nil {
			logger.Warn("Failed to add source line to %s: %v", defaultShell, err)
		} else {
			written++
		}
	}

	// If no default shell detected, try common files
	if written == 0 {
		for _, name := range []string{"zsh", "bash"} {
			if err := m.addSourceLine(name); err == nil {
				written++
			}
		}
	}

	// Always try fish config (non-fatal if fails)
	m.addSourceLine("fish")

	if written == 0 {
		logger.Warn("Could not add source line to any shell config file")
	}

	return nil
}

// detectConfiguredShells returns the list of shell config files containing the SVC source line.
func (m *Manager) detectConfiguredShells() []string {
	rcPath := m.cfg.RcFilePath()
	var configured []string

	for _, shell := range config.AvailableShells() {
		data, err := os.ReadFile(shell.FullPath)
		if err != nil {
			continue
		}
		// A line "sources" .svc.rc only if it both references .svc.rc AND
		// runs `source` (zsh/bash) or `source`-equivalent syntax. A bare
		// mention of ".svc.rc" (e.g. a user comment "# was .svc.rc") is NOT
		// a sourced line, so don't count it as configured. The exact rcPath
		// check remains the primary signal; the source+.svc.rc guard is the
		// fallback for shells where the rc path was written relatively.
		for _, line := range strings.Split(string(data), "\n") {
			if strings.Contains(line, rcPath) {
				configured = append(configured, shell.Name)
				break
			}
			if strings.Contains(line, "source") && strings.Contains(line, ".svc.rc") {
				configured = append(configured, shell.Name)
				break
			}
		}
	}

	return configured
}

// removeAllSourceLines removes the SVC source line from all shell config files.
func (m *Manager) removeAllSourceLines() error {
	rcPath := m.cfg.RcFilePath()

	for _, shell := range config.AvailableShells() {
		if err := removeSourceLineFromFile(shell.FullPath, rcPath); err != nil {
			logger.Warn("Failed to remove source line from %s: %v", shell.RcFile, err)
		}
	}

	// Also remove fish env file
	fishEnv := filepath.Join(m.cfg.SvcDir(), "env.sh.fish")
	os.Remove(fishEnv)

	return nil
}

// generateFishEnvContent builds the env.sh.fish content: the shims dir
// prepended to PATH plus ALL SDK env vars (JAVA_HOME, GOROOT, ...). Fish
// values are escaped with fishEscape; PATH keeps the trailing $PATH list so
// the existing PATH is preserved. Item 6.
func (m *Manager) generateFishEnvContent(envVars []envVarEntry) string {
	var lines []string
	lines = append(lines, "# SVC Environment Configuration (fish) - Auto-generated, do not edit manually")
	lines = append(lines, fmt.Sprintf("set -gx PATH %s $PATH", fishEscape(m.cfg.ShimsDir())))
	for _, e := range envVars {
		lines = append(lines, fmt.Sprintf("set -gx %s %s", e.Key, fishEscape(e.Value)))
	}
	return strings.Join(lines, "\n") + "\n"
}

// writeFishEnvFile regenerates env.sh.fish from the given env vars so fish
// users get both PATH and SDK env vars, kept in sync on every version
// switch (updateRcFile). No-op on Windows (see rcfile_windows.go).
func (m *Manager) writeFishEnvFile(envVars []envVarEntry) {
	fishRc := filepath.Join(m.cfg.SvcDir(), "env.sh.fish")
	if err := os.WriteFile(fishRc, []byte(m.generateFishEnvContent(envVars)), 0644); err != nil {
		logger.Warn("Failed to write fish env file: %v", err)
	}
}

// addSourceLine adds the SVC source line to a specific shell config file.
func (m *Manager) addSourceLine(shellName string) error {
	rcPath := m.cfg.RcFilePath()

	switch shellName {
	case "fish":
		// Write the full fish env file (PATH + SDK env vars), not just PATH.
		m.writeFishEnvFile(m.collectEnvVars())
		fishRc := filepath.Join(m.cfg.SvcDir(), "env.sh.fish")
		// Item 6: double-quote the paths so a space in the SVC dir doesn't
		// break the test/source line.
		fishSourceLine := fmt.Sprintf(`test -f "%s"; and source "%s"`, fishRc, fishRc)
		fishLegacyLine := fmt.Sprintf(`test -f %s; and source %s`, fishRc, fishRc)
		fishFile := filepath.Join(m.cfg.HomeDir(), ".config", "fish", "conf.d", "svc.fish")
		upgradeLegacySourceLine(fishFile, fishLegacyLine, fishSourceLine)
		return appendLineIfMissing(fishFile, fishSourceLine, fishSourceLine)

	case "zsh", "bash", "bash_profile", "profile", "zshenv":
		// Find the file path
		for _, shell := range config.AvailableShells() {
			if shell.Name == shellName {
				// Item 6: double-quote the paths (spaces in home dir).
				sourceLine := fmt.Sprintf(`[[ -f "%s" ]] && source "%s"`, rcPath, rcPath)
				legacyLine := fmt.Sprintf(`[[ -f %s ]] && source %s`, rcPath, rcPath)
				upgradeLegacySourceLine(shell.FullPath, legacyLine, sourceLine)
				return appendLineIfMissing(shell.FullPath, sourceLine, sourceLine)
			}
		}
		return fmt.Errorf("unknown shell: %s", shellName)

	case "powershell":
		// Not applicable on Unix
		return nil
	}

	return fmt.Errorf("unknown shell: %s", shellName)
}

// upgradeLegacySourceLine removes a legacy (unquoted) source line left by
// pre-quote-fix installs when the new quoted line is not present yet.
// Without this, the legacy line blocks the quoted replacement forever
// (appendLineIfMissing dedupes on substring) and paths containing spaces
// stay broken. Best-effort: any read/remove failure is non-fatal.
func upgradeLegacySourceLine(filePath, legacyLine, newLine string) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return
	}
	txt := string(data)
	if strings.Contains(txt, legacyLine) && !strings.Contains(txt, newLine) {
		_ = removeSourceLineFromFile(filePath, legacyLine)
	}
}

// appendLineIfMissing appends a line to a file if it doesn't already contain the check string.
func appendLineIfMissing(filePath, line, checkStr string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			// Create the file with the line
			dir := filepath.Dir(filePath)
			os.MkdirAll(dir, 0755)
			return os.WriteFile(filePath, []byte(line+"\n"), 0644)
		}
		return err
	}

	if strings.Contains(string(data), checkStr) {
		return nil // Already has the line
	}

	f, err := os.OpenFile(filePath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString("\n" + line + "\n")
	return err
}

// removeSourceLineFromFile removes all lines containing the check string from a file.
func removeSourceLineFromFile(filePath, checkStr string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	lines := strings.Split(string(data), "\n")
	var filtered []string
	removed := false
	for _, line := range lines {
		// Drop a line if it references the rc by exact path (the canonical
		// source line) OR both sources AND mentions .svc.rc. A bare
		// ".svc.rc" mention (e.g. a user comment "# was .svc.rc") does NOT
		// source the file, so it must be preserved — the previous broad
		// match stripped any line mentioning .svc.rc, silently erasing
		// user comments alongside the source line.
		if strings.Contains(line, checkStr) || (strings.Contains(line, "source") && strings.Contains(line, ".svc.rc")) {
			removed = true
			continue
		}
		filtered = append(filtered, line)
	}

	if !removed {
		return nil
	}

	// Backup before overwriting (O1: RC file non-atomic edit without backup).
	// If os.WriteFile fails or corrupts the file, the user can restore from .bak.
	backupFile(filePath)

	return os.WriteFile(filePath, []byte(strings.Join(filtered, "\n")), 0644)
}

// backupFile copies the file to a .svc.bak sibling before modifying it.
// Item 9: a previous .svc.bak is first rotated to .svc.bak.1 (one generation
// kept) instead of being silently overwritten — otherwise the second edit
// destroys the only backup of the original file.
// Non-fatal: if the backup fails (e.g. permissions), the modification still
// proceeds — the backup is defense-in-depth, not a gate.
func backupFile(filePath string) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return
	}
	bak := filePath + ".svc.bak"
	if _, err := os.Stat(bak); err == nil {
		// Best effort; if the rotation fails the fresh backup still lands.
		os.Rename(bak, bak+".1")
	}
	os.WriteFile(bak, data, 0644)
}
